---
title: "Painel de Monitoramento da Leptospirose"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    navbar:
      - {title: "Última atualização 20-04-2023", a7ign:right}
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)

# pacotes

pacman::p_load(
  flexdashboard,
  tidyverse,
  dygraphs,
  stringi,
  xts,
  rio,
  lubridate,
  here,
  stringr,
  Matrix,
  thematic,
  foreign,
  fs, 
  sf,
  epikit,
  shiny,
  plotly,
  geobr,
  DT,
  viridis) 

#import
lepto <- import("LEPTONET.DBF")


# classificação final 
lepto <- lepto %>% 
  mutate(classificacao = recode(CLASSI_FIN,
                                "1" = "Confirmado",
                                "2" = "Descartado",
                                "8" = "Ignorado"))

lepto <- lepto %>% 
  mutate(classificacao = replace_na(classificacao, "Suspeito"))


# Criando a variável de idade a partir da data de nascimento
lepto$idade <- as.numeric((lepto$DT_SIN_PRI - lepto$DT_NASC) /365)


# Faixa etária ----
lepto <- lepto %>% 
  mutate(faixa_etaria = age_categories(idade, 
                                       lower=0, 
                                       upper=60, 
                                       by=10))


# Semana epiemiológica ----


lepto <- lepto %>% 
  mutate(epi_semana = floor_date(DT_SIN_PRI, unit= "week"),
         Ano = floor_date(DT_SIN_PRI, unit = "year"),
         ano = substr(Ano, 1, 4),
         DT_SIN_PRI = as.Date(DT_SIN_PRI))



# Evolução ----
lepto <- lepto %>% 
  mutate(evolucao = recode(EVOLUCAO,
                           "1" = "Cura",
                           "2" = "Óbito por leptospirose",
                           "3" = "Óbito por outras causas",
                           "9" = "ignorado"))


# Raca ----
lepto <- lepto %>% 
  mutate(raca_cat = recode(CS_RACA,
                           # for reference: OLD = NEW
                           "1" = "Branca",
                           "2" = "Preta",
                           "3" = "Amarela",
                           "4" = "Parda",
                           "5" = "Indígena",
                           "9" = "Ignorado"))

# Sexo ----
lepto <- lepto |> 
  mutate(CS_SEXO = replace(CS_SEXO, CS_SEXO== "I",NA))                                    


lepto <- lepto %>% 
  mutate(sexo = recode(CS_SEXO,
                       # for reference: OLD = NEW
                       "F" = "Feminino",
                       "M" = "Masculino"))


# Escolaridade ----
lepto <- lepto %>% 
  mutate(escola = recode(CS_ESCOL_N,
                         # for reference: OLD = NEW
                         "00" = "Analfabeto",
                         "01" = "1 a  4 série incompleta",
                         "02" = "Até a 4 série completa",
                         "03" = "4 a 8 série incompleta",
                         "04" = "Ensino fundamental completo",
                         "05" = "Ensino Médio incompleto",
                         "06" = "Ensino Médio completo",
                         "07" = "EnsinoSuperior incompleto",
                         "08" = "Ensino Superior completo",
                         "09" = "Ignorado",
                         "10" = "Nao se aplica"))

## Gestante ----

lepto <- lepto %>% 
  mutate(gestante = recode(CS_GESTANT,
                           # for reference: OLD = NEW
                           "1" = "1 trimestre",
                           "2" = "2 trimestre",
                           "3" = "3 trimestre",
                           "4" = "Idade gestacional ignorada",
                           "5" = "Não",
                           "6" = "Não se aplica",
                           "9" = "Ignorado"))


## Hospitalização ----

lepto <- lepto %>% 
  mutate(hospital = recode(ATE_HOSP,
                           # for reference: OLD = NEW
                           "1" = "Sim",
                           "2" = "Nao",
                           "9" = "ignorado"))







```


# Menu {data-navmenu="menu"}

## Sidebar {.sidebar}

```{r}
# insere espaços
HTML("<br>")

selectInput("ano",  # nome do botao
            label = "Ano:",  
            selected = "2023",
            choices = unique(sort(lepto$ano))
            )

```


## Row 1

### Chart Notificações
```{r}

renderValueBox({
  
  lepto_ano <- lepto[which(lepto$ano == input$ano),]
  
  notificacoes <- lepto_ano %>% 
    count()  
  
   valueBox(
    value = notificacoes,
    caption = "Notificações",
    color = "steelblue")
})

    

```

### Chart Casos
```{r}

renderValueBox({
  
  lepto_ano <- lepto[which(lepto$ano == input$ano),]

  
  casos_confirmados <- lepto_ano %>% 
  filter(classificacao == "Confirmado") %>%
    count()  
  
  
   valueBox(
    value = casos_confirmados,
    caption = "Casos",
    color = "steelblue")
})

```

### Chart Descartados

```{r}

renderValueBox({
  
  lepto_ano <- lepto[which(lepto$ano == input$ano),]

  
  casos_descartados <- lepto_ano %>% 
  filter(classificacao == "Descartado") %>%
    count()  
  
  
   valueBox(
    value = casos_descartados,
    caption = "Descartados",
    color = "steelblue")
})


```


### Chart Suspeitos

```{r}

renderValueBox({
  
  lepto_ano <- lepto[which(lepto$ano == input$ano),]

  
  casos_suspeito <- lepto_ano %>% 
  filter(classificacao == "Suspeito") %>%
    count()  
  
  
   valueBox(
    value = casos_suspeito,
    caption = "Suspeitos",
    color = "steelblue")
})


```


### Chart Óbitos

```{r}

renderValueBox({
  
  lepto_ano <- lepto[which(lepto$ano == input$ano),]

  
  obitos <- lepto_ano %>% 
  filter(evolucao == "Óbito por leptospirose") %>%
    count()  
  
  
   valueBox(
    value = obitos,
    caption = "Obitos",
    color = "steelblue")
})

```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}


renderPlotly({

    lepto_ano <- lepto[which(lepto$ano == input$ano),] 

  
epicurva_semana <- lepto_ano %>% 
  filter(classificacao== "Confirmado") %>% 
  group_by(epi_semana) %>% 
  summarise(num_casos= n()) %>%   
ggplot(aes(x = epi_semana,
            y = num_casos, 
            text = paste0("Semana Epidemiológica: ", epi_semana, '\n', 
                   "Total: ", num_casos, "\n")
             )) +
  geom_bar(stat = "identity", 
           fill = "steelblue") +
  
  labs(x = "Semana Epidemiológica", y = "Número de Casos", title = "Número de Casos de Leptospirose por SE") +
  scale_x_date(date_breaks = "3 week", date_labels = "%U")+
  
  theme_minimal()+
  theme(text = element_text(family = "Times New Roman"),
        axis.text.x = element_text(face = "bold"),
        legend.position = "bottom",
        legend.text = element_text(size = 10))


ggplotly(epicurva_semana, tooltip = "text")

})
  
  
  


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

renderPlotly({

    lepto_ano <- lepto[which(lepto$ano == input$ano),] 

graf_sexo <- lepto_ano %>% 
  filter(classificacao== "Confirmado") %>% 
  group_by(sexo) %>% 
  summarise(num_casos= n()) %>% 
  ggplot(aes(x = sexo, y= num_casos)) +
  geom_bar(fill = "steelblue") +
  labs(x = "Sexo", y = "Frequência", title = "Distribuição por Sexo") +
  theme_minimal()

ggplotly(graf_sexo, tooltip = "text")

})
 
```

### Chart C

```{r}

```

